apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app: grafana
    project: observability
spec:
  project: observability
  destination:
    name: in-cluster
    namespace: grafana
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: grafana
    targetRevision: 10.3.2
    helm:
      releaseName: grafana
      valueFiles:
      - $values/argocd/addons/grafana/values.yaml
  - repoURL: 'https://github.com/marciorbr/gitops_aws_eks.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true