adminUser: admin
adminPassword: adminPassword        
        
persistence:
    enabled: true
    size: 10Gi
    storageClassName: dynamic-efs-sc
service:
    type: NodePort

ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.customer.com.br
initChownData:
    enabled: false